/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.filestash;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.resources.filestash.requests.FileStashDownloadFileRequest;
import java.io.InputStream;

public class FileStashClient {
    protected final ClientOptions clientOptions;

    private final RawFileStashClient rawClient;

    public FileStashClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawFileStashClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawFileStashClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Download a file from File Stash
     */
    public InputStream downloadFile(FileStashDownloadFileRequest request) {
        return this.rawClient.downloadFile(request).body();
    }

    /**
     * Download a file from File Stash
     */
    public InputStream downloadFile(FileStashDownloadFileRequest request, RequestOptions requestOptions) {
        return this.rawClient.downloadFile(request, requestOptions).body();
    }
}
