/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.appoverrides;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.appoverrides.requests.AppOverridesListRequest;
import com.pipedream.api.resources.appoverrides.requests.CreateAppOverrideOpts;
import com.pipedream.api.resources.appoverrides.requests.UpdateAppOverrideOpts;
import com.pipedream.api.types.AppOverride;

public class AppOverridesClient {
    protected final ClientOptions clientOptions;

    private final RawAppOverridesClient rawClient;

    public AppOverridesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAppOverridesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAppOverridesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public SyncPagingIterable<AppOverride> list() {
        return this.rawClient.list().body();
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public SyncPagingIterable<AppOverride> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public SyncPagingIterable<AppOverride> list(AppOverridesListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public SyncPagingIterable<AppOverride> list(AppOverridesListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Create an app override with pre-defined custom field values
     */
    public AppOverride create(CreateAppOverrideOpts request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create an app override with pre-defined custom field values
     */
    public AppOverride create(CreateAppOverrideOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Get the configuration of a specific app override
     */
    public AppOverride retrieve(String id) {
        return this.rawClient.retrieve(id).body();
    }

    /**
     * Get the configuration of a specific app override
     */
    public AppOverride retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).body();
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public AppOverride update(String id) {
        return this.rawClient.update(id).body();
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public AppOverride update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).body();
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public AppOverride update(String id, UpdateAppOverrideOpts request) {
        return this.rawClient.update(id, request).body();
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public AppOverride update(String id, UpdateAppOverrideOpts request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }

    /**
     * Delete an app override without affecting accounts already connected with it
     */
    public void delete(String id) {
        this.rawClient.delete(id).body();
    }

    /**
     * Delete an app override without affecting accounts already connected with it
     */
    public void delete(String id, RequestOptions requestOptions) {
        this.rawClient.delete(id, requestOptions).body();
    }
}
