/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.appoverrides;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.appoverrides.requests.AppOverridesListRequest;
import com.pipedream.api.resources.appoverrides.requests.CreateAppOverrideOpts;
import com.pipedream.api.resources.appoverrides.requests.UpdateAppOverrideOpts;
import com.pipedream.api.types.AppOverride;
import java.util.concurrent.CompletableFuture;

public class AsyncAppOverridesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAppOverridesClient rawClient;

    public AsyncAppOverridesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAppOverridesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAppOverridesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public CompletableFuture<SyncPagingIterable<AppOverride>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public CompletableFuture<SyncPagingIterable<AppOverride>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public CompletableFuture<SyncPagingIterable<AppOverride>> list(AppOverridesListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * List the app overrides available to the project, including the parent workspace's
     */
    public CompletableFuture<SyncPagingIterable<AppOverride>> list(
            AppOverridesListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create an app override with pre-defined custom field values
     */
    public CompletableFuture<AppOverride> create(CreateAppOverrideOpts request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create an app override with pre-defined custom field values
     */
    public CompletableFuture<AppOverride> create(CreateAppOverrideOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get the configuration of a specific app override
     */
    public CompletableFuture<AppOverride> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Get the configuration of a specific app override
     */
    public CompletableFuture<AppOverride> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public CompletableFuture<AppOverride> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public CompletableFuture<AppOverride> update(String id, RequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public CompletableFuture<AppOverride> update(String id, UpdateAppOverrideOpts request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Update an app override's name, custom field values, or OAuth client selection
     */
    public CompletableFuture<AppOverride> update(
            String id, UpdateAppOverrideOpts request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete an app override without affecting accounts already connected with it
     */
    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Delete an app override without affecting accounts already connected with it
     */
    public CompletableFuture<Void> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }
}
