/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.willktrial.api.resources.pets;

import com.willktrial.api.core.ClientOptions;
import com.willktrial.api.core.RequestOptions;
import com.willktrial.api.resources.pets.requests.CreatePetRequest;
import com.willktrial.api.resources.pets.requests.ListPetsRequest;
import com.willktrial.api.types.Pet;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncPetsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPetsClient rawClient;

    public AsyncPetsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPetsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPetsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<List<Pet>> listPets() {
        return this.rawClient.listPets().thenApply(response -> response.body());
    }

    public CompletableFuture<List<Pet>> listPets(ListPetsRequest request) {
        return this.rawClient.listPets(request).thenApply(response -> response.body());
    }

    public CompletableFuture<List<Pet>> listPets(ListPetsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPets(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Pet> createPet(CreatePetRequest request) {
        return this.rawClient.createPet(request).thenApply(response -> response.body());
    }

    public CompletableFuture<Pet> createPet(CreatePetRequest request, RequestOptions requestOptions) {
        return this.rawClient.createPet(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Pet> getPet(String petId) {
        return this.rawClient.getPet(petId).thenApply(response -> response.body());
    }

    public CompletableFuture<Pet> getPet(String petId, RequestOptions requestOptions) {
        return this.rawClient.getPet(petId, requestOptions).thenApply(response -> response.body());
    }
}
