/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.willktrial.api.resources.pets;

import com.willktrial.api.core.ClientOptions;
import com.willktrial.api.core.RequestOptions;
import com.willktrial.api.resources.pets.requests.CreatePetRequest;
import com.willktrial.api.resources.pets.requests.ListPetsRequest;
import com.willktrial.api.types.Pet;
import java.util.List;

public class PetsClient {
    protected final ClientOptions clientOptions;

    private final RawPetsClient rawClient;

    public PetsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPetsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPetsClient withRawResponse() {
        return this.rawClient;
    }

    public List<Pet> listPets() {
        return this.rawClient.listPets().body();
    }

    public List<Pet> listPets(ListPetsRequest request) {
        return this.rawClient.listPets(request).body();
    }

    public List<Pet> listPets(ListPetsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPets(request, requestOptions).body();
    }

    public Pet createPet(CreatePetRequest request) {
        return this.rawClient.createPet(request).body();
    }

    public Pet createPet(CreatePetRequest request, RequestOptions requestOptions) {
        return this.rawClient.createPet(request, requestOptions).body();
    }

    public Pet getPet(String petId) {
        return this.rawClient.getPet(petId).body();
    }

    public Pet getPet(String petId, RequestOptions requestOptions) {
        return this.rawClient.getPet(petId, requestOptions).body();
    }
}
