/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.willktrial.api.resources.pets;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.willktrial.api.core.BaseClientApiException;
import com.willktrial.api.core.BaseClientException;
import com.willktrial.api.core.BaseClientHttpResponse;
import com.willktrial.api.core.ClientOptions;
import com.willktrial.api.core.MediaTypes;
import com.willktrial.api.core.ObjectMappers;
import com.willktrial.api.core.QueryStringMapper;
import com.willktrial.api.core.RequestOptions;
import com.willktrial.api.resources.pets.requests.CreatePetRequest;
import com.willktrial.api.resources.pets.requests.ListPetsRequest;
import com.willktrial.api.types.Pet;
import java.io.IOException;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPetsClient {
    protected final ClientOptions clientOptions;

    public RawPetsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public BaseClientHttpResponse<List<Pet>> listPets() {
        return listPets(ListPetsRequest.builder().build());
    }

    public BaseClientHttpResponse<List<Pet>> listPets(ListPetsRequest request) {
        return listPets(request, null);
    }

    public BaseClientHttpResponse<List<Pet>> listPets(ListPetsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pets");
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new BaseClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), new TypeReference<List<Pet>>() {}),
                        response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new BaseClientApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new BaseClientException("Network error executing HTTP request", e);
        }
    }

    public BaseClientHttpResponse<Pet> createPet(CreatePetRequest request) {
        return createPet(request, null);
    }

    public BaseClientHttpResponse<Pet> createPet(CreatePetRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pets")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new BaseClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new BaseClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Pet.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new BaseClientApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new BaseClientException("Network error executing HTTP request", e);
        }
    }

    public BaseClientHttpResponse<Pet> getPet(String petId) {
        return getPet(petId, null);
    }

    public BaseClientHttpResponse<Pet> getPet(String petId, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pets")
                .addPathSegment(petId)
                .build();
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new BaseClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Pet.class), response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            throw new BaseClientApiException(
                    "Error with status code " + response.code(),
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                    response);
        } catch (IOException e) {
            throw new BaseClientException("Network error executing HTTP request", e);
        }
    }
}
