/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.filestash.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FileStashDownloadFileRequest.Builder.class)
public final class FileStashDownloadFileRequest {
    private final String s3Key;

    private final Map<String, Object> additionalProperties;

    private FileStashDownloadFileRequest(String s3Key, Map<String, Object> additionalProperties) {
        this.s3Key = s3Key;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("s3_key")
    public String getS3Key() {
        return s3Key;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FileStashDownloadFileRequest && equalTo((FileStashDownloadFileRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FileStashDownloadFileRequest other) {
        return s3Key.equals(other.s3Key);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.s3Key);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static S3KeyStage builder() {
        return new Builder();
    }

    public interface S3KeyStage {
        _FinalStage s3Key(@NotNull String s3Key);

        Builder from(FileStashDownloadFileRequest other);
    }

    public interface _FinalStage {
        FileStashDownloadFileRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements S3KeyStage, _FinalStage {
        private String s3Key;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FileStashDownloadFileRequest other) {
            s3Key(other.getS3Key());
            return this;
        }

        @java.lang.Override
        @JsonSetter("s3_key")
        public _FinalStage s3Key(@NotNull String s3Key) {
            this.s3Key = Objects.requireNonNull(s3Key, "s3Key must not be null");
            return this;
        }

        @java.lang.Override
        public FileStashDownloadFileRequest build() {
            return new FileStashDownloadFileRequest(s3Key, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
