/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConfiguredPropValueApp.Builder.class)
public final class ConfiguredPropValueApp {
    private final String authProvisionId;

    private final Map<String, Object> additionalProperties;

    private ConfiguredPropValueApp(String authProvisionId, Map<String, Object> additionalProperties) {
        this.authProvisionId = authProvisionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authProvisionId")
    public String getAuthProvisionId() {
        return authProvisionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfiguredPropValueApp && equalTo((ConfiguredPropValueApp) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConfiguredPropValueApp other) {
        return authProvisionId.equals(other.authProvisionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authProvisionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AuthProvisionIdStage builder() {
        return new Builder();
    }

    public interface AuthProvisionIdStage {
        _FinalStage authProvisionId(@NotNull String authProvisionId);

        Builder from(ConfiguredPropValueApp other);
    }

    public interface _FinalStage {
        ConfiguredPropValueApp build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AuthProvisionIdStage, _FinalStage {
        private String authProvisionId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ConfiguredPropValueApp other) {
            authProvisionId(other.getAuthProvisionId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("authProvisionId")
        public _FinalStage authProvisionId(@NotNull String authProvisionId) {
            this.authProvisionId = Objects.requireNonNull(authProvisionId, "authProvisionId must not be null");
            return this;
        }

        @java.lang.Override
        public ConfiguredPropValueApp build() {
            return new ConfiguredPropValueApp(authProvisionId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
