/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ConfigurablePropType {
    public static final ConfigurablePropType AIRTABLE_VIEW_ID =
            new ConfigurablePropType(Value.AIRTABLE_VIEW_ID, "$.airtable.viewId");

    public static final ConfigurablePropType APP = new ConfigurablePropType(Value.APP, "app");

    public static final ConfigurablePropType AIRTABLE_BASE_ID =
            new ConfigurablePropType(Value.AIRTABLE_BASE_ID, "$.airtable.baseId");

    public static final ConfigurablePropType AIRTABLE_TABLE_ID =
            new ConfigurablePropType(Value.AIRTABLE_TABLE_ID, "$.airtable.tableId");

    public static final ConfigurablePropType BOOLEAN = new ConfigurablePropType(Value.BOOLEAN, "boolean");

    public static final ConfigurablePropType INTERFACE_TIMER =
            new ConfigurablePropType(Value.INTERFACE_TIMER, "$.interface.timer");

    public static final ConfigurablePropType ANY = new ConfigurablePropType(Value.ANY, "any");

    public static final ConfigurablePropType SERVICE_DB = new ConfigurablePropType(Value.SERVICE_DB, "$.service.db");

    public static final ConfigurablePropType SQL = new ConfigurablePropType(Value.SQL, "sql");

    public static final ConfigurablePropType AIRTABLE_FIELD_ID =
            new ConfigurablePropType(Value.AIRTABLE_FIELD_ID, "$.airtable.fieldId");

    public static final ConfigurablePropType STRING_ARRAY = new ConfigurablePropType(Value.STRING_ARRAY, "string[]");

    public static final ConfigurablePropType DISCORD_CHANNEL_ARRAY =
            new ConfigurablePropType(Value.DISCORD_CHANNEL_ARRAY, "$.discord.channel[]");

    public static final ConfigurablePropType OBJECT = new ConfigurablePropType(Value.OBJECT, "object");

    public static final ConfigurablePropType INTERFACE_APPHOOK =
            new ConfigurablePropType(Value.INTERFACE_APPHOOK, "$.interface.apphook");

    public static final ConfigurablePropType ALERT = new ConfigurablePropType(Value.ALERT, "alert");

    public static final ConfigurablePropType STRING = new ConfigurablePropType(Value.STRING, "string");

    public static final ConfigurablePropType INTEGER = new ConfigurablePropType(Value.INTEGER, "integer");

    public static final ConfigurablePropType DISCORD_CHANNEL =
            new ConfigurablePropType(Value.DISCORD_CHANNEL, "$.discord.channel");

    public static final ConfigurablePropType INTEGER_ARRAY = new ConfigurablePropType(Value.INTEGER_ARRAY, "integer[]");

    public static final ConfigurablePropType DATA_STORE = new ConfigurablePropType(Value.DATA_STORE, "data_store");

    public static final ConfigurablePropType HTTP_REQUEST =
            new ConfigurablePropType(Value.HTTP_REQUEST, "http_request");

    public static final ConfigurablePropType DIR = new ConfigurablePropType(Value.DIR, "dir");

    public static final ConfigurablePropType INTERFACE_HTTP =
            new ConfigurablePropType(Value.INTERFACE_HTTP, "$.interface.http");

    private final Value value;

    private final String string;

    ConfigurablePropType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ConfigurablePropType && this.string.equals(((ConfigurablePropType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case AIRTABLE_VIEW_ID:
                return visitor.visitAirtableViewId();
            case APP:
                return visitor.visitApp();
            case AIRTABLE_BASE_ID:
                return visitor.visitAirtableBaseId();
            case AIRTABLE_TABLE_ID:
                return visitor.visitAirtableTableId();
            case BOOLEAN:
                return visitor.visitBoolean();
            case INTERFACE_TIMER:
                return visitor.visitInterfaceTimer();
            case ANY:
                return visitor.visitAny();
            case SERVICE_DB:
                return visitor.visitServiceDb();
            case SQL:
                return visitor.visitSql();
            case AIRTABLE_FIELD_ID:
                return visitor.visitAirtableFieldId();
            case STRING_ARRAY:
                return visitor.visitStringArray();
            case DISCORD_CHANNEL_ARRAY:
                return visitor.visitDiscordChannelArray();
            case OBJECT:
                return visitor.visitObject();
            case INTERFACE_APPHOOK:
                return visitor.visitInterfaceApphook();
            case ALERT:
                return visitor.visitAlert();
            case STRING:
                return visitor.visitString();
            case INTEGER:
                return visitor.visitInteger();
            case DISCORD_CHANNEL:
                return visitor.visitDiscordChannel();
            case INTEGER_ARRAY:
                return visitor.visitIntegerArray();
            case DATA_STORE:
                return visitor.visitDataStore();
            case HTTP_REQUEST:
                return visitor.visitHttpRequest();
            case DIR:
                return visitor.visitDir();
            case INTERFACE_HTTP:
                return visitor.visitInterfaceHttp();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ConfigurablePropType valueOf(String value) {
        switch (value) {
            case "$.airtable.viewId":
                return AIRTABLE_VIEW_ID;
            case "app":
                return APP;
            case "$.airtable.baseId":
                return AIRTABLE_BASE_ID;
            case "$.airtable.tableId":
                return AIRTABLE_TABLE_ID;
            case "boolean":
                return BOOLEAN;
            case "$.interface.timer":
                return INTERFACE_TIMER;
            case "any":
                return ANY;
            case "$.service.db":
                return SERVICE_DB;
            case "sql":
                return SQL;
            case "$.airtable.fieldId":
                return AIRTABLE_FIELD_ID;
            case "string[]":
                return STRING_ARRAY;
            case "$.discord.channel[]":
                return DISCORD_CHANNEL_ARRAY;
            case "object":
                return OBJECT;
            case "$.interface.apphook":
                return INTERFACE_APPHOOK;
            case "alert":
                return ALERT;
            case "string":
                return STRING;
            case "integer":
                return INTEGER;
            case "$.discord.channel":
                return DISCORD_CHANNEL;
            case "integer[]":
                return INTEGER_ARRAY;
            case "data_store":
                return DATA_STORE;
            case "http_request":
                return HTTP_REQUEST;
            case "dir":
                return DIR;
            case "$.interface.http":
                return INTERFACE_HTTP;
            default:
                return new ConfigurablePropType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AIRTABLE_BASE_ID,

        AIRTABLE_FIELD_ID,

        AIRTABLE_TABLE_ID,

        AIRTABLE_VIEW_ID,

        DISCORD_CHANNEL,

        DISCORD_CHANNEL_ARRAY,

        INTERFACE_APPHOOK,

        INTERFACE_HTTP,

        INTERFACE_TIMER,

        SERVICE_DB,

        ALERT,

        ANY,

        APP,

        BOOLEAN,

        DATA_STORE,

        DIR,

        HTTP_REQUEST,

        INTEGER,

        INTEGER_ARRAY,

        OBJECT,

        SQL,

        STRING,

        STRING_ARRAY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAirtableBaseId();

        T visitAirtableFieldId();

        T visitAirtableTableId();

        T visitAirtableViewId();

        T visitDiscordChannel();

        T visitDiscordChannelArray();

        T visitInterfaceApphook();

        T visitInterfaceHttp();

        T visitInterfaceTimer();

        T visitServiceDb();

        T visitAlert();

        T visitAny();

        T visitApp();

        T visitBoolean();

        T visitDataStore();

        T visitDir();

        T visitHttpRequest();

        T visitInteger();

        T visitIntegerArray();

        T visitObject();

        T visitSql();

        T visitString();

        T visitStringArray();

        T visitUnknown(String unknownType);
    }
}
