/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.pipedream.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(using = ConfigurablePropSqlOptionsItem.Deserializer.class)
public final class ConfigurablePropSqlOptionsItem {
    private final Object value;

    private final int type;

    private ConfigurablePropSqlOptionsItem(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((PropOption) this.value);
        } else if (this.type == 1) {
            return visitor.visit((PropOptionNested) this.value);
        } else if (this.type == 2) {
            return visitor.visit((Optional<PropOptionValue>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfigurablePropSqlOptionsItem && equalTo((ConfigurablePropSqlOptionsItem) other);
    }

    private boolean equalTo(ConfigurablePropSqlOptionsItem other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ConfigurablePropSqlOptionsItem of(PropOption value) {
        return new ConfigurablePropSqlOptionsItem(value, 0);
    }

    public static ConfigurablePropSqlOptionsItem of(PropOptionNested value) {
        return new ConfigurablePropSqlOptionsItem(value, 1);
    }

    public static ConfigurablePropSqlOptionsItem of(Optional<PropOptionValue> value) {
        return new ConfigurablePropSqlOptionsItem(value, 2);
    }

    public interface Visitor<T> {
        T visit(PropOption value);

        T visit(PropOptionNested value);

        T visit(Optional<PropOptionValue> value);
    }

    static final class Deserializer extends StdDeserializer<ConfigurablePropSqlOptionsItem> {
        Deserializer() {
            super(ConfigurablePropSqlOptionsItem.class);
        }

        @java.lang.Override
        public ConfigurablePropSqlOptionsItem deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, PropOption.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, PropOptionNested.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, new TypeReference<Optional<PropOptionValue>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
