/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.pipedream.api.core.ObjectMappers;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = ConfiguredPropsValue.Deserializer.class)
public final class ConfiguredPropsValue {
    private final Object value;

    private final int type;

    private ConfiguredPropsValue(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((Object) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ConfiguredPropApp) this.value);
        } else if (this.type == 2) {
            return visitor.visit((ConfiguredPropSql) this.value);
        } else if (this.type == 3) {
            return visitor.visit((boolean) this.value);
        } else if (this.type == 4) {
            return visitor.visit((double) this.value);
        } else if (this.type == 5) {
            return visitor.visit((Map<String, Object>) this.value);
        } else if (this.type == 6) {
            return visitor.visit((String) this.value);
        } else if (this.type == 7) {
            return visitor.visit((List<String>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfiguredPropsValue && equalTo((ConfiguredPropsValue) other);
    }

    private boolean equalTo(ConfiguredPropsValue other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ConfiguredPropsValue of(Object value) {
        return new ConfiguredPropsValue(value, 0);
    }

    public static ConfiguredPropsValue of(ConfiguredPropApp value) {
        return new ConfiguredPropsValue(value, 1);
    }

    public static ConfiguredPropsValue of(ConfiguredPropSql value) {
        return new ConfiguredPropsValue(value, 2);
    }

    public static ConfiguredPropsValue of(boolean value) {
        return new ConfiguredPropsValue(value, 3);
    }

    public static ConfiguredPropsValue of(double value) {
        return new ConfiguredPropsValue(value, 4);
    }

    public static ConfiguredPropsValue of(Map<String, Object> value) {
        return new ConfiguredPropsValue(value, 5);
    }

    public static ConfiguredPropsValue of(String value) {
        return new ConfiguredPropsValue(value, 6);
    }

    public static ConfiguredPropsValue of(List<String> value) {
        return new ConfiguredPropsValue(value, 7);
    }

    public interface Visitor<T> {
        T visit(Object value);

        T visit(ConfiguredPropApp value);

        T visit(ConfiguredPropSql value);

        T visit(boolean value);

        T visit(double value);

        T visit(Map<String, Object> value);

        T visit(String value);

        T visit(List<String> value);
    }

    static final class Deserializer extends StdDeserializer<ConfiguredPropsValue> {
        Deserializer() {
            super(ConfiguredPropsValue.class);
        }

        @java.lang.Override
        public ConfiguredPropsValue deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, Object.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ConfiguredPropApp.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ConfiguredPropSql.class));
            } catch (RuntimeException e) {
            }
            if (value instanceof Boolean) {
                return of((Boolean) value);
            }
            if (value instanceof Double) {
                return of((Double) value);
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<Map<String, Object>>() {}));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
