/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.Nullable;
import com.pipedream.api.core.NullableNonemptyFilter;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConfigurePropResponse.Builder.class)
public final class ConfigurePropResponse {
    private final Optional<List<ConfigurePropOptionsItem>> options;

    private final Optional<List<String>> stringOptions;

    private final Optional<List<Observation>> observations;

    private final Optional<Map<String, Object>> context;

    private final Optional<List<String>> errors;

    private final Map<String, Object> additionalProperties;

    private ConfigurePropResponse(
            Optional<List<ConfigurePropOptionsItem>> options,
            Optional<List<String>> stringOptions,
            Optional<List<Observation>> observations,
            Optional<Map<String, Object>> context,
            Optional<List<String>> errors,
            Map<String, Object> additionalProperties) {
        this.options = options;
        this.stringOptions = stringOptions;
        this.observations = observations;
        this.context = context;
        this.errors = errors;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<List<ConfigurePropOptionsItem>> getOptions() {
        if (options == null) {
            return Optional.empty();
        }
        return options;
    }

    /**
     * @return Available options for the configured prop
     */
    @JsonIgnore
    public Optional<List<String>> getStringOptions() {
        if (stringOptions == null) {
            return Optional.empty();
        }
        return stringOptions;
    }

    @JsonIgnore
    public Optional<List<Observation>> getObservations() {
        if (observations == null) {
            return Optional.empty();
        }
        return observations;
    }

    /**
     * @return New context after configuring the prop
     */
    @JsonIgnore
    public Optional<Map<String, Object>> getContext() {
        if (context == null) {
            return Optional.empty();
        }
        return context;
    }

    /**
     * @return Any errors that occurred during configuration
     */
    @JsonProperty("errors")
    public Optional<List<String>> getErrors() {
        return errors;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("options")
    private Optional<List<ConfigurePropOptionsItem>> _getOptions() {
        return options;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("string_options")
    private Optional<List<String>> _getStringOptions() {
        return stringOptions;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("observations")
    private Optional<List<Observation>> _getObservations() {
        return observations;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("context")
    private Optional<Map<String, Object>> _getContext() {
        return context;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfigurePropResponse && equalTo((ConfigurePropResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConfigurePropResponse other) {
        return options.equals(other.options)
                && stringOptions.equals(other.stringOptions)
                && observations.equals(other.observations)
                && context.equals(other.context)
                && errors.equals(other.errors);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.options, this.stringOptions, this.observations, this.context, this.errors);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ConfigurePropOptionsItem>> options = Optional.empty();

        private Optional<List<String>> stringOptions = Optional.empty();

        private Optional<List<Observation>> observations = Optional.empty();

        private Optional<Map<String, Object>> context = Optional.empty();

        private Optional<List<String>> errors = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConfigurePropResponse other) {
            options(other.getOptions());
            stringOptions(other.getStringOptions());
            observations(other.getObservations());
            context(other.getContext());
            errors(other.getErrors());
            return this;
        }

        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<List<ConfigurePropOptionsItem>> options) {
            this.options = options;
            return this;
        }

        public Builder options(List<ConfigurePropOptionsItem> options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        public Builder options(Nullable<List<ConfigurePropOptionsItem>> options) {
            if (options.isNull()) {
                this.options = null;
            } else if (options.isEmpty()) {
                this.options = Optional.empty();
            } else {
                this.options = Optional.of(options.get());
            }
            return this;
        }

        /**
         * <p>Available options for the configured prop</p>
         */
        @JsonSetter(value = "string_options", nulls = Nulls.SKIP)
        public Builder stringOptions(Optional<List<String>> stringOptions) {
            this.stringOptions = stringOptions;
            return this;
        }

        public Builder stringOptions(List<String> stringOptions) {
            this.stringOptions = Optional.ofNullable(stringOptions);
            return this;
        }

        public Builder stringOptions(Nullable<List<String>> stringOptions) {
            if (stringOptions.isNull()) {
                this.stringOptions = null;
            } else if (stringOptions.isEmpty()) {
                this.stringOptions = Optional.empty();
            } else {
                this.stringOptions = Optional.of(stringOptions.get());
            }
            return this;
        }

        @JsonSetter(value = "observations", nulls = Nulls.SKIP)
        public Builder observations(Optional<List<Observation>> observations) {
            this.observations = observations;
            return this;
        }

        public Builder observations(List<Observation> observations) {
            this.observations = Optional.ofNullable(observations);
            return this;
        }

        public Builder observations(Nullable<List<Observation>> observations) {
            if (observations.isNull()) {
                this.observations = null;
            } else if (observations.isEmpty()) {
                this.observations = Optional.empty();
            } else {
                this.observations = Optional.of(observations.get());
            }
            return this;
        }

        /**
         * <p>New context after configuring the prop</p>
         */
        @JsonSetter(value = "context", nulls = Nulls.SKIP)
        public Builder context(Optional<Map<String, Object>> context) {
            this.context = context;
            return this;
        }

        public Builder context(Map<String, Object> context) {
            this.context = Optional.ofNullable(context);
            return this;
        }

        public Builder context(Nullable<Map<String, Object>> context) {
            if (context.isNull()) {
                this.context = null;
            } else if (context.isEmpty()) {
                this.context = Optional.empty();
            } else {
                this.context = Optional.of(context.get());
            }
            return this;
        }

        /**
         * <p>Any errors that occurred during configuration</p>
         */
        @JsonSetter(value = "errors", nulls = Nulls.SKIP)
        public Builder errors(Optional<List<String>> errors) {
            this.errors = errors;
            return this;
        }

        public Builder errors(List<String> errors) {
            this.errors = Optional.ofNullable(errors);
            return this;
        }

        public ConfigurePropResponse build() {
            return new ConfigurePropResponse(
                    options, stringOptions, observations, context, errors, additionalProperties);
        }
    }
}
