/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.pipedream.api.core.ObjectMappers;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = ConfiguredPropValue.Deserializer.class)
public final class ConfiguredPropValue {
    private final Object value;

    private final int type;

    private ConfiguredPropValue(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ConfiguredPropValueAny) this.value);
        } else if (this.type == 1) {
            return visitor.visit((ConfiguredPropValueApp) this.value);
        } else if (this.type == 2) {
            return visitor.visit((boolean) this.value);
        } else if (this.type == 3) {
            return visitor.visit((double) this.value);
        } else if (this.type == 4) {
            return visitor.visit((Map<String, Object>) this.value);
        } else if (this.type == 5) {
            return visitor.visit((ConfiguredPropValueSql) this.value);
        } else if (this.type == 6) {
            return visitor.visit((String) this.value);
        } else if (this.type == 7) {
            return visitor.visit((List<String>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfiguredPropValue && equalTo((ConfiguredPropValue) other);
    }

    private boolean equalTo(ConfiguredPropValue other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ConfiguredPropValue of(ConfiguredPropValueAny value) {
        return new ConfiguredPropValue(value, 0);
    }

    public static ConfiguredPropValue of(ConfiguredPropValueApp value) {
        return new ConfiguredPropValue(value, 1);
    }

    public static ConfiguredPropValue of(boolean value) {
        return new ConfiguredPropValue(value, 2);
    }

    public static ConfiguredPropValue of(double value) {
        return new ConfiguredPropValue(value, 3);
    }

    public static ConfiguredPropValue of(Map<String, Object> value) {
        return new ConfiguredPropValue(value, 4);
    }

    public static ConfiguredPropValue of(ConfiguredPropValueSql value) {
        return new ConfiguredPropValue(value, 5);
    }

    public static ConfiguredPropValue of(String value) {
        return new ConfiguredPropValue(value, 6);
    }

    public static ConfiguredPropValue of(List<String> value) {
        return new ConfiguredPropValue(value, 7);
    }

    public interface Visitor<T> {
        T visit(ConfiguredPropValueAny value);

        T visit(ConfiguredPropValueApp value);

        T visit(boolean value);

        T visit(double value);

        T visit(Map<String, Object> value);

        T visit(ConfiguredPropValueSql value);

        T visit(String value);

        T visit(List<String> value);
    }

    static final class Deserializer extends StdDeserializer<ConfiguredPropValue> {
        Deserializer() {
            super(ConfiguredPropValue.class);
        }

        @java.lang.Override
        public ConfiguredPropValue deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Boolean) {
                return of((Boolean) value);
            }
            if (value instanceof Double) {
                return of((Double) value);
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ConfiguredPropValueAny.class));
            } catch (RuntimeException e) {
            }
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("authProvisionId")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, ConfiguredPropValueApp.class));
                } catch (RuntimeException e) {
                }
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<Map<String, Object>>() {}));
            } catch (RuntimeException e) {
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("value")
                    && ((Map<?, ?>) value).containsKey("query")
                    && ((Map<?, ?>) value).containsKey("params")
                    && ((Map<?, ?>) value).containsKey("usePreparedStatements")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, ConfiguredPropValueSql.class));
                } catch (RuntimeException e) {
                }
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<String>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
