/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConfigurablePropSqlAuth.Builder.class)
public final class ConfigurablePropSqlAuth {
    private final Optional<String> app;

    private final Map<String, Object> additionalProperties;

    private ConfigurablePropSqlAuth(Optional<String> app, Map<String, Object> additionalProperties) {
        this.app = app;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The app that provides SQL authentication
     */
    @JsonProperty("app")
    public Optional<String> getApp() {
        return app;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfigurablePropSqlAuth && equalTo((ConfigurablePropSqlAuth) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConfigurablePropSqlAuth other) {
        return app.equals(other.app);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.app);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> app = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConfigurablePropSqlAuth other) {
            app(other.getApp());
            return this;
        }

        /**
         * <p>The app that provides SQL authentication</p>
         */
        @JsonSetter(value = "app", nulls = Nulls.SKIP)
        public Builder app(Optional<String> app) {
            this.app = app;
            return this;
        }

        public Builder app(String app) {
            this.app = Optional.ofNullable(app);
            return this;
        }

        public ConfigurablePropSqlAuth build() {
            return new ConfigurablePropSqlAuth(app, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
