/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.pipedream.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = ConfigurePropOptionsItem.Deserializer.class)
public final class ConfigurePropOptionsItem {
    private final Object value;

    private final int type;

    private ConfigurePropOptionsItem(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((PropOption) this.value);
        } else if (this.type == 1) {
            return visitor.visit((PropOptionNested) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConfigurePropOptionsItem && equalTo((ConfigurePropOptionsItem) other);
    }

    private boolean equalTo(ConfigurePropOptionsItem other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ConfigurePropOptionsItem of(PropOption value) {
        return new ConfigurePropOptionsItem(value, 0);
    }

    public static ConfigurePropOptionsItem of(PropOptionNested value) {
        return new ConfigurePropOptionsItem(value, 1);
    }

    public interface Visitor<T> {
        T visit(PropOption value);

        T visit(PropOptionNested value);
    }

    static final class Deserializer extends StdDeserializer<ConfigurePropOptionsItem> {
        Deserializer() {
            super(ConfigurePropOptionsItem.class);
        }

        @java.lang.Override
        public ConfigurePropOptionsItem deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("label")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, PropOption.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?> && ((Map<?, ?>) value).containsKey("__lv")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(value, PropOptionNested.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
