/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DeployTriggerResult.Builder.class)
public final class DeployTriggerResult {
    private final Optional<String> webhookSigningKey;

    private final Map<String, Object> additionalProperties;

    private DeployTriggerResult(Optional<String> webhookSigningKey, Map<String, Object> additionalProperties) {
        this.webhookSigningKey = webhookSigningKey;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The webhook signing key. Only returned for OAuth-authenticated requests when <code>webhook_url</code> is supplied.
     */
    @JsonProperty("webhook_signing_key")
    public Optional<String> getWebhookSigningKey() {
        return webhookSigningKey;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DeployTriggerResult && equalTo((DeployTriggerResult) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DeployTriggerResult other) {
        return webhookSigningKey.equals(other.webhookSigningKey);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.webhookSigningKey);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> webhookSigningKey = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DeployTriggerResult other) {
            webhookSigningKey(other.getWebhookSigningKey());
            return this;
        }

        /**
         * <p>The webhook signing key. Only returned for OAuth-authenticated requests when <code>webhook_url</code> is supplied.</p>
         */
        @JsonSetter(value = "webhook_signing_key", nulls = Nulls.SKIP)
        public Builder webhookSigningKey(Optional<String> webhookSigningKey) {
            this.webhookSigningKey = webhookSigningKey;
            return this;
        }

        public Builder webhookSigningKey(String webhookSigningKey) {
            this.webhookSigningKey = Optional.ofNullable(webhookSigningKey);
            return this;
        }

        public DeployTriggerResult build() {
            return new DeployTriggerResult(webhookSigningKey, additionalProperties);
        }
    }
}
