/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = DynamicProps.Builder.class)
public final class DynamicProps {
    private final Optional<String> id;

    private final Optional<List<ConfigurableProp>> configurableProps;

    private final Map<String, Object> additionalProperties;

    private DynamicProps(
            Optional<String> id,
            Optional<List<ConfigurableProp>> configurableProps,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.configurableProps = configurableProps;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique ID of the dynamic prop
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return The updated configurable properties
     */
    @JsonProperty("configurableProps")
    public Optional<List<ConfigurableProp>> getConfigurableProps() {
        return configurableProps;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof DynamicProps && equalTo((DynamicProps) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(DynamicProps other) {
        return id.equals(other.id) && configurableProps.equals(other.configurableProps);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.configurableProps);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<List<ConfigurableProp>> configurableProps = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(DynamicProps other) {
            id(other.getId());
            configurableProps(other.getConfigurableProps());
            return this;
        }

        /**
         * <p>The unique ID of the dynamic prop</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>The updated configurable properties</p>
         */
        @JsonSetter(value = "configurableProps", nulls = Nulls.SKIP)
        public Builder configurableProps(Optional<List<ConfigurableProp>> configurableProps) {
            this.configurableProps = configurableProps;
            return this;
        }

        public Builder configurableProps(List<ConfigurableProp> configurableProps) {
            this.configurableProps = Optional.ofNullable(configurableProps);
            return this;
        }

        public DynamicProps build() {
            return new DynamicProps(id, configurableProps, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
