/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EmitterType {
    public static final EmitterType EMAIL = new EmitterType(Value.EMAIL, "email");

    public static final EmitterType SOURCE = new EmitterType(Value.SOURCE, "source");

    public static final EmitterType HTTP = new EmitterType(Value.HTTP, "http");

    public static final EmitterType TIMER = new EmitterType(Value.TIMER, "timer");

    private final Value value;

    private final String string;

    EmitterType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other) || (other instanceof EmitterType && this.string.equals(((EmitterType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EMAIL:
                return visitor.visitEmail();
            case SOURCE:
                return visitor.visitSource();
            case HTTP:
                return visitor.visitHttp();
            case TIMER:
                return visitor.visitTimer();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EmitterType valueOf(String value) {
        switch (value) {
            case "email":
                return EMAIL;
            case "source":
                return SOURCE;
            case "http":
                return HTTP;
            case "timer":
                return TIMER;
            default:
                return new EmitterType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EMAIL,

        HTTP,

        SOURCE,

        TIMER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEmail();

        T visitHttp();

        T visitSource();

        T visitTimer();

        T visitUnknown(String unknownType);
    }
}
