/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetTriggerWebhooksResponse.Builder.class)
public final class GetTriggerWebhooksResponse {
    private final List<String> webhookUrls;

    private final Optional<List<TriggerWebhook>> webhooks;

    private final Map<String, Object> additionalProperties;

    private GetTriggerWebhooksResponse(
            List<String> webhookUrls,
            Optional<List<TriggerWebhook>> webhooks,
            Map<String, Object> additionalProperties) {
        this.webhookUrls = webhookUrls;
        this.webhooks = webhooks;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("webhook_urls")
    public List<String> getWebhookUrls() {
        return webhookUrls;
    }

    /**
     * @return Webhook objects for the configured URLs. <code>signing_key</code> is only returned for OAuth-authenticated requests.
     */
    @JsonProperty("webhooks")
    public Optional<List<TriggerWebhook>> getWebhooks() {
        return webhooks;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetTriggerWebhooksResponse && equalTo((GetTriggerWebhooksResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetTriggerWebhooksResponse other) {
        return webhookUrls.equals(other.webhookUrls) && webhooks.equals(other.webhooks);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.webhookUrls, this.webhooks);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<String> webhookUrls = new ArrayList<>();

        private Optional<List<TriggerWebhook>> webhooks = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetTriggerWebhooksResponse other) {
            webhookUrls(other.getWebhookUrls());
            webhooks(other.getWebhooks());
            return this;
        }

        @JsonSetter(value = "webhook_urls", nulls = Nulls.SKIP)
        public Builder webhookUrls(List<String> webhookUrls) {
            this.webhookUrls.clear();
            if (webhookUrls != null) {
                this.webhookUrls.addAll(webhookUrls);
            }
            return this;
        }

        public Builder addWebhookUrls(String webhookUrls) {
            this.webhookUrls.add(webhookUrls);
            return this;
        }

        public Builder addAllWebhookUrls(List<String> webhookUrls) {
            if (webhookUrls != null) {
                this.webhookUrls.addAll(webhookUrls);
            }
            return this;
        }

        /**
         * <p>Webhook objects for the configured URLs. <code>signing_key</code> is only returned for OAuth-authenticated requests.</p>
         */
        @JsonSetter(value = "webhooks", nulls = Nulls.SKIP)
        public Builder webhooks(Optional<List<TriggerWebhook>> webhooks) {
            this.webhooks = webhooks;
            return this;
        }

        public Builder webhooks(List<TriggerWebhook> webhooks) {
            this.webhooks = Optional.ofNullable(webhooks);
            return this;
        }

        public GetTriggerWebhooksResponse build() {
            return new GetTriggerWebhooksResponse(webhookUrls, webhooks, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
