/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HttpRequestConfig.Builder.class)
public final class HttpRequestConfig {
    private final Optional<HttpRequestAuth> auth;

    private final Optional<HttpRequestBody> body;

    private final Optional<List<HttpRequestField>> headers;

    private final Optional<List<HttpRequestField>> params;

    private final Optional<String> tab;

    private final Optional<String> method;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private HttpRequestConfig(
            Optional<HttpRequestAuth> auth,
            Optional<HttpRequestBody> body,
            Optional<List<HttpRequestField>> headers,
            Optional<List<HttpRequestField>> params,
            Optional<String> tab,
            Optional<String> method,
            Optional<String> url,
            Map<String, Object> additionalProperties) {
        this.auth = auth;
        this.body = body;
        this.headers = headers;
        this.params = params;
        this.tab = tab;
        this.method = method;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("auth")
    public Optional<HttpRequestAuth> getAuth() {
        return auth;
    }

    @JsonProperty("body")
    public Optional<HttpRequestBody> getBody() {
        return body;
    }

    @JsonProperty("headers")
    public Optional<List<HttpRequestField>> getHeaders() {
        return headers;
    }

    @JsonProperty("params")
    public Optional<List<HttpRequestField>> getParams() {
        return params;
    }

    @JsonProperty("tab")
    public Optional<String> getTab() {
        return tab;
    }

    @JsonProperty("method")
    public Optional<String> getMethod() {
        return method;
    }

    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HttpRequestConfig && equalTo((HttpRequestConfig) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HttpRequestConfig other) {
        return auth.equals(other.auth)
                && body.equals(other.body)
                && headers.equals(other.headers)
                && params.equals(other.params)
                && tab.equals(other.tab)
                && method.equals(other.method)
                && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.auth, this.body, this.headers, this.params, this.tab, this.method, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<HttpRequestAuth> auth = Optional.empty();

        private Optional<HttpRequestBody> body = Optional.empty();

        private Optional<List<HttpRequestField>> headers = Optional.empty();

        private Optional<List<HttpRequestField>> params = Optional.empty();

        private Optional<String> tab = Optional.empty();

        private Optional<String> method = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(HttpRequestConfig other) {
            auth(other.getAuth());
            body(other.getBody());
            headers(other.getHeaders());
            params(other.getParams());
            tab(other.getTab());
            method(other.getMethod());
            url(other.getUrl());
            return this;
        }

        @JsonSetter(value = "auth", nulls = Nulls.SKIP)
        public Builder auth(Optional<HttpRequestAuth> auth) {
            this.auth = auth;
            return this;
        }

        public Builder auth(HttpRequestAuth auth) {
            this.auth = Optional.ofNullable(auth);
            return this;
        }

        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public Builder body(Optional<HttpRequestBody> body) {
            this.body = body;
            return this;
        }

        public Builder body(HttpRequestBody body) {
            this.body = Optional.ofNullable(body);
            return this;
        }

        @JsonSetter(value = "headers", nulls = Nulls.SKIP)
        public Builder headers(Optional<List<HttpRequestField>> headers) {
            this.headers = headers;
            return this;
        }

        public Builder headers(List<HttpRequestField> headers) {
            this.headers = Optional.ofNullable(headers);
            return this;
        }

        @JsonSetter(value = "params", nulls = Nulls.SKIP)
        public Builder params(Optional<List<HttpRequestField>> params) {
            this.params = params;
            return this;
        }

        public Builder params(List<HttpRequestField> params) {
            this.params = Optional.ofNullable(params);
            return this;
        }

        @JsonSetter(value = "tab", nulls = Nulls.SKIP)
        public Builder tab(Optional<String> tab) {
            this.tab = tab;
            return this;
        }

        public Builder tab(String tab) {
            this.tab = Optional.ofNullable(tab);
            return this;
        }

        @JsonSetter(value = "method", nulls = Nulls.SKIP)
        public Builder method(Optional<String> method) {
            this.method = method;
            return this;
        }

        public Builder method(String method) {
            this.method = Optional.ofNullable(method);
            return this;
        }

        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        public HttpRequestConfig build() {
            return new HttpRequestConfig(auth, body, headers, params, tab, method, url, additionalProperties);
        }
    }
}
