/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HttpRequestAuth.Builder.class)
public final class HttpRequestAuth {
    private final Optional<HttpRequestAuthType> type;

    private final Optional<String> username;

    private final Optional<String> password;

    private final Optional<String> token;

    private final Map<String, Object> additionalProperties;

    private HttpRequestAuth(
            Optional<HttpRequestAuthType> type,
            Optional<String> username,
            Optional<String> password,
            Optional<String> token,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.username = username;
        this.password = password;
        this.token = token;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The authentication type
     */
    @JsonProperty("type")
    public Optional<HttpRequestAuthType> getType() {
        return type;
    }

    @JsonProperty("username")
    public Optional<String> getUsername() {
        return username;
    }

    @JsonProperty("password")
    public Optional<String> getPassword() {
        return password;
    }

    @JsonProperty("token")
    public Optional<String> getToken() {
        return token;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HttpRequestAuth && equalTo((HttpRequestAuth) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HttpRequestAuth other) {
        return type.equals(other.type)
                && username.equals(other.username)
                && password.equals(other.password)
                && token.equals(other.token);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.username, this.password, this.token);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<HttpRequestAuthType> type = Optional.empty();

        private Optional<String> username = Optional.empty();

        private Optional<String> password = Optional.empty();

        private Optional<String> token = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(HttpRequestAuth other) {
            type(other.getType());
            username(other.getUsername());
            password(other.getPassword());
            token(other.getToken());
            return this;
        }

        /**
         * <p>The authentication type</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<HttpRequestAuthType> type) {
            this.type = type;
            return this;
        }

        public Builder type(HttpRequestAuthType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        @JsonSetter(value = "username", nulls = Nulls.SKIP)
        public Builder username(Optional<String> username) {
            this.username = username;
            return this;
        }

        public Builder username(String username) {
            this.username = Optional.ofNullable(username);
            return this;
        }

        @JsonSetter(value = "password", nulls = Nulls.SKIP)
        public Builder password(Optional<String> password) {
            this.password = password;
            return this;
        }

        public Builder password(String password) {
            this.password = Optional.ofNullable(password);
            return this;
        }

        @JsonSetter(value = "token", nulls = Nulls.SKIP)
        public Builder token(Optional<String> token) {
            this.token = token;
            return this;
        }

        public Builder token(String token) {
            this.token = Optional.ofNullable(token);
            return this;
        }

        public HttpRequestAuth build() {
            return new HttpRequestAuth(type, username, password, token, additionalProperties);
        }
    }
}
