/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HttpInterface.Builder.class)
public final class HttpInterface {
    private final String id;

    private final String key;

    private final String endpointUrl;

    private final boolean customResponse;

    private final int createdAt;

    private final int updatedAt;

    private final Map<String, Object> additionalProperties;

    private HttpInterface(
            String id,
            String key,
            String endpointUrl,
            boolean customResponse,
            int createdAt,
            int updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.key = key;
        this.endpointUrl = endpointUrl;
        this.customResponse = customResponse;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique ID of the HTTP interface
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("key")
    public String getKey() {
        return key;
    }

    @JsonProperty("endpoint_url")
    public String getEndpointUrl() {
        return endpointUrl;
    }

    @JsonProperty("custom_response")
    public boolean getCustomResponse() {
        return customResponse;
    }

    /**
     * @return The timestamp when the HTTP interface was created (epoch milliseconds)
     */
    @JsonProperty("created_at")
    public int getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The timestamp when the HTTP interface was last updated (epoch milliseconds)
     */
    @JsonProperty("updated_at")
    public int getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HttpInterface && equalTo((HttpInterface) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HttpInterface other) {
        return id.equals(other.id)
                && key.equals(other.key)
                && endpointUrl.equals(other.endpointUrl)
                && customResponse == other.customResponse
                && createdAt == other.createdAt
                && updatedAt == other.updatedAt;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.key, this.endpointUrl, this.customResponse, this.createdAt, this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique ID of the HTTP interface</p>
         */
        KeyStage id(@NotNull String id);

        Builder from(HttpInterface other);
    }

    public interface KeyStage {
        EndpointUrlStage key(@NotNull String key);
    }

    public interface EndpointUrlStage {
        CustomResponseStage endpointUrl(@NotNull String endpointUrl);
    }

    public interface CustomResponseStage {
        CreatedAtStage customResponse(boolean customResponse);
    }

    public interface CreatedAtStage {
        /**
         * <p>The timestamp when the HTTP interface was created (epoch milliseconds)</p>
         */
        UpdatedAtStage createdAt(int createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>The timestamp when the HTTP interface was last updated (epoch milliseconds)</p>
         */
        _FinalStage updatedAt(int updatedAt);
    }

    public interface _FinalStage {
        HttpInterface build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage,
                    KeyStage,
                    EndpointUrlStage,
                    CustomResponseStage,
                    CreatedAtStage,
                    UpdatedAtStage,
                    _FinalStage {
        private String id;

        private String key;

        private String endpointUrl;

        private boolean customResponse;

        private int createdAt;

        private int updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(HttpInterface other) {
            id(other.getId());
            key(other.getKey());
            endpointUrl(other.getEndpointUrl());
            customResponse(other.getCustomResponse());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>The unique ID of the HTTP interface</p>
         * <p>The unique ID of the HTTP interface</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public KeyStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("key")
        public EndpointUrlStage key(@NotNull String key) {
            this.key = Objects.requireNonNull(key, "key must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("endpoint_url")
        public CustomResponseStage endpointUrl(@NotNull String endpointUrl) {
            this.endpointUrl = Objects.requireNonNull(endpointUrl, "endpointUrl must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("custom_response")
        public CreatedAtStage customResponse(boolean customResponse) {
            this.customResponse = customResponse;
            return this;
        }

        /**
         * <p>The timestamp when the HTTP interface was created (epoch milliseconds)</p>
         * <p>The timestamp when the HTTP interface was created (epoch milliseconds)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(int createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * <p>The timestamp when the HTTP interface was last updated (epoch milliseconds)</p>
         * <p>The timestamp when the HTTP interface was last updated (epoch milliseconds)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(int updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.Override
        public HttpInterface build() {
            return new HttpInterface(id, key, endpointUrl, customResponse, createdAt, updatedAt, additionalProperties);
        }
    }
}
