/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ObservationError.Builder.class)
public final class ObservationError {
    private final Optional<String> name;

    private final Optional<String> message;

    private final Optional<String> stack;

    private final Map<String, Object> additionalProperties;

    private ObservationError(
            Optional<String> name,
            Optional<String> message,
            Optional<String> stack,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.message = message;
        this.stack = stack;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the error/exception
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return The error message
     */
    @JsonProperty("message")
    public Optional<String> getMessage() {
        return message;
    }

    /**
     * @return The stack trace of the error
     */
    @JsonProperty("stack")
    public Optional<String> getStack() {
        return stack;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ObservationError && equalTo((ObservationError) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ObservationError other) {
        return name.equals(other.name) && message.equals(other.message) && stack.equals(other.stack);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.message, this.stack);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<String> message = Optional.empty();

        private Optional<String> stack = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ObservationError other) {
            name(other.getName());
            message(other.getMessage());
            stack(other.getStack());
            return this;
        }

        /**
         * <p>The name of the error/exception</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>The error message</p>
         */
        @JsonSetter(value = "message", nulls = Nulls.SKIP)
        public Builder message(Optional<String> message) {
            this.message = message;
            return this;
        }

        public Builder message(String message) {
            this.message = Optional.ofNullable(message);
            return this;
        }

        /**
         * <p>The stack trace of the error</p>
         */
        @JsonSetter(value = "stack", nulls = Nulls.SKIP)
        public Builder stack(Optional<String> stack) {
            this.stack = stack;
            return this;
        }

        public Builder stack(String stack) {
            this.stack = Optional.ofNullable(stack);
            return this;
        }

        public ObservationError build() {
            return new ObservationError(name, message, stack, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
