/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ProjectInfoResponseApp.Builder.class)
public final class ProjectInfoResponseApp {
    private final Optional<String> id;

    private final Optional<String> nameSlug;

    private final Map<String, Object> additionalProperties;

    private ProjectInfoResponseApp(
            Optional<String> id, Optional<String> nameSlug, Map<String, Object> additionalProperties) {
        this.id = id;
        this.nameSlug = nameSlug;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the app. Only applies for OAuth apps.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return The name slug of the target app
     */
    @JsonProperty("name_slug")
    public Optional<String> getNameSlug() {
        return nameSlug;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ProjectInfoResponseApp && equalTo((ProjectInfoResponseApp) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ProjectInfoResponseApp other) {
        return id.equals(other.id) && nameSlug.equals(other.nameSlug);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.nameSlug);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> nameSlug = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ProjectInfoResponseApp other) {
            id(other.getId());
            nameSlug(other.getNameSlug());
            return this;
        }

        /**
         * <p>ID of the app. Only applies for OAuth apps.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>The name slug of the target app</p>
         */
        @JsonSetter(value = "name_slug", nulls = Nulls.SKIP)
        public Builder nameSlug(Optional<String> nameSlug) {
            this.nameSlug = nameSlug;
            return this;
        }

        public Builder nameSlug(String nameSlug) {
            this.nameSlug = Optional.ofNullable(nameSlug);
            return this;
        }

        public ProjectInfoResponseApp build() {
            return new ProjectInfoResponseApp(id, nameSlug, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
