/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PropOptionNested.Builder.class)
public final class PropOptionNested {
    private final PropOption lv;

    private final Map<String, Object> additionalProperties;

    private PropOptionNested(PropOption lv, Map<String, Object> additionalProperties) {
        this.lv = lv;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("__lv")
    public PropOption getLv() {
        return lv;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PropOptionNested && equalTo((PropOptionNested) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PropOptionNested other) {
        return lv.equals(other.lv);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.lv);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static LvStage builder() {
        return new Builder();
    }

    public interface LvStage {
        _FinalStage lv(@NotNull PropOption lv);

        Builder from(PropOptionNested other);
    }

    public interface _FinalStage {
        PropOptionNested build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements LvStage, _FinalStage {
        private PropOption lv;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PropOptionNested other) {
            lv(other.getLv());
            return this;
        }

        @java.lang.Override
        @JsonSetter("__lv")
        public _FinalStage lv(@NotNull PropOption lv) {
            this.lv = Objects.requireNonNull(lv, "lv must not be null");
            return this;
        }

        @java.lang.Override
        public PropOptionNested build() {
            return new PropOptionNested(lv, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
