/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.Nullable;
import com.pipedream.api.core.NullableNonemptyFilter;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ToolAnnotations.Builder.class)
public final class ToolAnnotations {
    private final Optional<Boolean> destructiveHint;

    private final Optional<Boolean> idempotentHint;

    private final Optional<Boolean> openWorldHint;

    private final Optional<Boolean> readOnlyHint;

    private final Optional<String> title;

    private final Map<String, Object> additionalProperties;

    private ToolAnnotations(
            Optional<Boolean> destructiveHint,
            Optional<Boolean> idempotentHint,
            Optional<Boolean> openWorldHint,
            Optional<Boolean> readOnlyHint,
            Optional<String> title,
            Map<String, Object> additionalProperties) {
        this.destructiveHint = destructiveHint;
        this.idempotentHint = idempotentHint;
        this.openWorldHint = openWorldHint;
        this.readOnlyHint = readOnlyHint;
        this.title = title;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return If true, the component may perform destructive updates to its environment. If false, the component performs only additive updates.
     */
    @JsonIgnore
    public Optional<Boolean> getDestructiveHint() {
        if (destructiveHint == null) {
            return Optional.empty();
        }
        return destructiveHint;
    }

    /**
     * @return If true, calling the component repeatedly with the same arguments will have no additional effect on the its environment.
     */
    @JsonIgnore
    public Optional<Boolean> getIdempotentHint() {
        if (idempotentHint == null) {
            return Optional.empty();
        }
        return idempotentHint;
    }

    /**
     * @return If true, this component may interact with an “open world” of external entities. If false, the component's domain of interaction is closed. For example, the world of a web search component is open, whereas that of a memory component is not.
     */
    @JsonIgnore
    public Optional<Boolean> getOpenWorldHint() {
        if (openWorldHint == null) {
            return Optional.empty();
        }
        return openWorldHint;
    }

    /**
     * @return If true, the component does not modify its environment.
     */
    @JsonIgnore
    public Optional<Boolean> getReadOnlyHint() {
        if (readOnlyHint == null) {
            return Optional.empty();
        }
        return readOnlyHint;
    }

    /**
     * @return A human-readable title for the component.
     */
    @JsonIgnore
    public Optional<String> getTitle() {
        if (title == null) {
            return Optional.empty();
        }
        return title;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("destructiveHint")
    private Optional<Boolean> _getDestructiveHint() {
        return destructiveHint;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("idempotentHint")
    private Optional<Boolean> _getIdempotentHint() {
        return idempotentHint;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("openWorldHint")
    private Optional<Boolean> _getOpenWorldHint() {
        return openWorldHint;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("readOnlyHint")
    private Optional<Boolean> _getReadOnlyHint() {
        return readOnlyHint;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("title")
    private Optional<String> _getTitle() {
        return title;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ToolAnnotations && equalTo((ToolAnnotations) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ToolAnnotations other) {
        return destructiveHint.equals(other.destructiveHint)
                && idempotentHint.equals(other.idempotentHint)
                && openWorldHint.equals(other.openWorldHint)
                && readOnlyHint.equals(other.readOnlyHint)
                && title.equals(other.title);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.destructiveHint, this.idempotentHint, this.openWorldHint, this.readOnlyHint, this.title);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> destructiveHint = Optional.empty();

        private Optional<Boolean> idempotentHint = Optional.empty();

        private Optional<Boolean> openWorldHint = Optional.empty();

        private Optional<Boolean> readOnlyHint = Optional.empty();

        private Optional<String> title = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ToolAnnotations other) {
            destructiveHint(other.getDestructiveHint());
            idempotentHint(other.getIdempotentHint());
            openWorldHint(other.getOpenWorldHint());
            readOnlyHint(other.getReadOnlyHint());
            title(other.getTitle());
            return this;
        }

        /**
         * <p>If true, the component may perform destructive updates to its environment. If false, the component performs only additive updates.</p>
         */
        @JsonSetter(value = "destructiveHint", nulls = Nulls.SKIP)
        public Builder destructiveHint(Optional<Boolean> destructiveHint) {
            this.destructiveHint = destructiveHint;
            return this;
        }

        public Builder destructiveHint(Boolean destructiveHint) {
            this.destructiveHint = Optional.ofNullable(destructiveHint);
            return this;
        }

        public Builder destructiveHint(Nullable<Boolean> destructiveHint) {
            if (destructiveHint.isNull()) {
                this.destructiveHint = null;
            } else if (destructiveHint.isEmpty()) {
                this.destructiveHint = Optional.empty();
            } else {
                this.destructiveHint = Optional.of(destructiveHint.get());
            }
            return this;
        }

        /**
         * <p>If true, calling the component repeatedly with the same arguments will have no additional effect on the its environment.</p>
         */
        @JsonSetter(value = "idempotentHint", nulls = Nulls.SKIP)
        public Builder idempotentHint(Optional<Boolean> idempotentHint) {
            this.idempotentHint = idempotentHint;
            return this;
        }

        public Builder idempotentHint(Boolean idempotentHint) {
            this.idempotentHint = Optional.ofNullable(idempotentHint);
            return this;
        }

        public Builder idempotentHint(Nullable<Boolean> idempotentHint) {
            if (idempotentHint.isNull()) {
                this.idempotentHint = null;
            } else if (idempotentHint.isEmpty()) {
                this.idempotentHint = Optional.empty();
            } else {
                this.idempotentHint = Optional.of(idempotentHint.get());
            }
            return this;
        }

        /**
         * <p>If true, this component may interact with an “open world” of external entities. If false, the component's domain of interaction is closed. For example, the world of a web search component is open, whereas that of a memory component is not.</p>
         */
        @JsonSetter(value = "openWorldHint", nulls = Nulls.SKIP)
        public Builder openWorldHint(Optional<Boolean> openWorldHint) {
            this.openWorldHint = openWorldHint;
            return this;
        }

        public Builder openWorldHint(Boolean openWorldHint) {
            this.openWorldHint = Optional.ofNullable(openWorldHint);
            return this;
        }

        public Builder openWorldHint(Nullable<Boolean> openWorldHint) {
            if (openWorldHint.isNull()) {
                this.openWorldHint = null;
            } else if (openWorldHint.isEmpty()) {
                this.openWorldHint = Optional.empty();
            } else {
                this.openWorldHint = Optional.of(openWorldHint.get());
            }
            return this;
        }

        /**
         * <p>If true, the component does not modify its environment.</p>
         */
        @JsonSetter(value = "readOnlyHint", nulls = Nulls.SKIP)
        public Builder readOnlyHint(Optional<Boolean> readOnlyHint) {
            this.readOnlyHint = readOnlyHint;
            return this;
        }

        public Builder readOnlyHint(Boolean readOnlyHint) {
            this.readOnlyHint = Optional.ofNullable(readOnlyHint);
            return this;
        }

        public Builder readOnlyHint(Nullable<Boolean> readOnlyHint) {
            if (readOnlyHint.isNull()) {
                this.readOnlyHint = null;
            } else if (readOnlyHint.isEmpty()) {
                this.readOnlyHint = Optional.empty();
            } else {
                this.readOnlyHint = Optional.of(readOnlyHint.get());
            }
            return this;
        }

        /**
         * <p>A human-readable title for the component.</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        public Builder title(Nullable<String> title) {
            if (title.isNull()) {
                this.title = null;
            } else if (title.isEmpty()) {
                this.title = Optional.empty();
            } else {
                this.title = Optional.of(title.get());
            }
            return this;
        }

        public ToolAnnotations build() {
            return new ToolAnnotations(
                    destructiveHint, idempotentHint, openWorldHint, readOnlyHint, title, additionalProperties);
        }
    }
}
