/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Webhook.Builder.class)
public final class Webhook {
    private final String id;

    private final String url;

    private final boolean signingKeySet;

    private final int createdAt;

    private final int updatedAt;

    private final Map<String, Object> additionalProperties;

    private Webhook(
            String id,
            String url,
            boolean signingKeySet,
            int createdAt,
            int updatedAt,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.url = url;
        this.signingKeySet = signingKeySet;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The unique ID of the webhook
     */
    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return The webhook URL
     */
    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    /**
     * @return Whether a signing key has been set for this webhook
     */
    @JsonProperty("signing_key_set")
    public boolean getSigningKeySet() {
        return signingKeySet;
    }

    /**
     * @return The time the webhook was created, in epoch seconds
     */
    @JsonProperty("created_at")
    public int getCreatedAt() {
        return createdAt;
    }

    /**
     * @return The time the webhook was last updated, in epoch seconds
     */
    @JsonProperty("updated_at")
    public int getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Webhook && equalTo((Webhook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Webhook other) {
        return id.equals(other.id)
                && url.equals(other.url)
                && signingKeySet == other.signingKeySet
                && createdAt == other.createdAt
                && updatedAt == other.updatedAt;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.url, this.signingKeySet, this.createdAt, this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static IdStage builder() {
        return new Builder();
    }

    public interface IdStage {
        /**
         * <p>The unique ID of the webhook</p>
         */
        UrlStage id(@NotNull String id);

        Builder from(Webhook other);
    }

    public interface UrlStage {
        /**
         * <p>The webhook URL</p>
         */
        SigningKeySetStage url(@NotNull String url);
    }

    public interface SigningKeySetStage {
        /**
         * <p>Whether a signing key has been set for this webhook</p>
         */
        CreatedAtStage signingKeySet(boolean signingKeySet);
    }

    public interface CreatedAtStage {
        /**
         * <p>The time the webhook was created, in epoch seconds</p>
         */
        UpdatedAtStage createdAt(int createdAt);
    }

    public interface UpdatedAtStage {
        /**
         * <p>The time the webhook was last updated, in epoch seconds</p>
         */
        _FinalStage updatedAt(int updatedAt);
    }

    public interface _FinalStage {
        Webhook build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements IdStage, UrlStage, SigningKeySetStage, CreatedAtStage, UpdatedAtStage, _FinalStage {
        private String id;

        private String url;

        private boolean signingKeySet;

        private int createdAt;

        private int updatedAt;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(Webhook other) {
            id(other.getId());
            url(other.getUrl());
            signingKeySet(other.getSigningKeySet());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        /**
         * <p>The unique ID of the webhook</p>
         * <p>The unique ID of the webhook</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("id")
        public UrlStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>The webhook URL</p>
         * <p>The webhook URL</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("url")
        public SigningKeySetStage url(@NotNull String url) {
            this.url = Objects.requireNonNull(url, "url must not be null");
            return this;
        }

        /**
         * <p>Whether a signing key has been set for this webhook</p>
         * <p>Whether a signing key has been set for this webhook</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("signing_key_set")
        public CreatedAtStage signingKeySet(boolean signingKeySet) {
            this.signingKeySet = signingKeySet;
            return this;
        }

        /**
         * <p>The time the webhook was created, in epoch seconds</p>
         * <p>The time the webhook was created, in epoch seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("created_at")
        public UpdatedAtStage createdAt(int createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * <p>The time the webhook was last updated, in epoch seconds</p>
         * <p>The time the webhook was last updated, in epoch seconds</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updated_at")
        public _FinalStage updatedAt(int updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.Override
        public Webhook build() {
            return new Webhook(id, url, signingKeySet, createdAt, updatedAt, additionalProperties);
        }
    }
}
