/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.apps.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ListAppsRequestSortKey {
    public static final ListAppsRequestSortKey NAME_SLUG = new ListAppsRequestSortKey(Value.NAME_SLUG, "name_slug");

    public static final ListAppsRequestSortKey FEATURED_WEIGHT =
            new ListAppsRequestSortKey(Value.FEATURED_WEIGHT, "featured_weight");

    public static final ListAppsRequestSortKey NAME = new ListAppsRequestSortKey(Value.NAME, "name");

    private final Value value;

    private final String string;

    ListAppsRequestSortKey(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ListAppsRequestSortKey
                        && this.string.equals(((ListAppsRequestSortKey) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case NAME_SLUG:
                return visitor.visitNameSlug();
            case FEATURED_WEIGHT:
                return visitor.visitFeaturedWeight();
            case NAME:
                return visitor.visitName();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ListAppsRequestSortKey valueOf(String value) {
        switch (value) {
            case "name_slug":
                return NAME_SLUG;
            case "featured_weight":
                return FEATURED_WEIGHT;
            case "name":
                return NAME;
            default:
                return new ListAppsRequestSortKey(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NAME,

        NAME_SLUG,

        FEATURED_WEIGHT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitName();

        T visitNameSlug();

        T visitFeaturedWeight();

        T visitUnknown(String unknownType);
    }
}
