/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.tokens.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokensValidateRequest.Builder.class)
public final class TokensValidateRequest {
    private final String appId;

    private final Optional<String> accountId;

    private final Optional<String> oauthAppId;

    private final Map<String, Object> additionalProperties;

    private TokensValidateRequest(
            String appId,
            Optional<String> accountId,
            Optional<String> oauthAppId,
            Map<String, Object> additionalProperties) {
        this.appId = appId;
        this.accountId = accountId;
        this.oauthAppId = oauthAppId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The app ID to validate against
     */
    @JsonProperty("app_id")
    public String getAppId() {
        return appId;
    }

    /**
     * @return An existing account ID to reconnect. Must belong to the app identified by app_id.
     */
    @JsonProperty("account_id")
    public Optional<String> getAccountId() {
        return accountId;
    }

    /**
     * @return The OAuth app ID to validate against (if the token is for an OAuth app)
     */
    @JsonProperty("oauth_app_id")
    public Optional<String> getOauthAppId() {
        return oauthAppId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokensValidateRequest && equalTo((TokensValidateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokensValidateRequest other) {
        return appId.equals(other.appId) && accountId.equals(other.accountId) && oauthAppId.equals(other.oauthAppId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.appId, this.accountId, this.oauthAppId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AppIdStage builder() {
        return new Builder();
    }

    public interface AppIdStage {
        /**
         * <p>The app ID to validate against</p>
         */
        _FinalStage appId(@NotNull String appId);

        Builder from(TokensValidateRequest other);
    }

    public interface _FinalStage {
        TokensValidateRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>An existing account ID to reconnect. Must belong to the app identified by app_id.</p>
         */
        _FinalStage accountId(Optional<String> accountId);

        _FinalStage accountId(String accountId);

        /**
         * <p>The OAuth app ID to validate against (if the token is for an OAuth app)</p>
         */
        _FinalStage oauthAppId(Optional<String> oauthAppId);

        _FinalStage oauthAppId(String oauthAppId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AppIdStage, _FinalStage {
        private String appId;

        private Optional<String> oauthAppId = Optional.empty();

        private Optional<String> accountId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(TokensValidateRequest other) {
            appId(other.getAppId());
            accountId(other.getAccountId());
            oauthAppId(other.getOauthAppId());
            return this;
        }

        /**
         * <p>The app ID to validate against</p>
         * <p>The app ID to validate against</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("app_id")
        public _FinalStage appId(@NotNull String appId) {
            this.appId = Objects.requireNonNull(appId, "appId must not be null");
            return this;
        }

        /**
         * <p>The OAuth app ID to validate against (if the token is for an OAuth app)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage oauthAppId(String oauthAppId) {
            this.oauthAppId = Optional.ofNullable(oauthAppId);
            return this;
        }

        /**
         * <p>The OAuth app ID to validate against (if the token is for an OAuth app)</p>
         */
        @java.lang.Override
        @JsonSetter(value = "oauth_app_id", nulls = Nulls.SKIP)
        public _FinalStage oauthAppId(Optional<String> oauthAppId) {
            this.oauthAppId = oauthAppId;
            return this;
        }

        /**
         * <p>An existing account ID to reconnect. Must belong to the app identified by app_id.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage accountId(String accountId) {
            this.accountId = Optional.ofNullable(accountId);
            return this;
        }

        /**
         * <p>An existing account ID to reconnect. Must belong to the app identified by app_id.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "account_id", nulls = Nulls.SKIP)
        public _FinalStage accountId(Optional<String> accountId) {
            this.accountId = accountId;
            return this;
        }

        @java.lang.Override
        public TokensValidateRequest build() {
            return new TokensValidateRequest(appId, accountId, oauthAppId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
