/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.tokens.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TokensValidateRequest.Builder.class)
public final class TokensValidateRequest {
    private final Optional<String> appId;

    private final Optional<String> accountId;

    private final Optional<String> oauthAppId;

    private final Optional<String> appOverrideId;

    private final Map<String, Object> additionalProperties;

    private TokensValidateRequest(
            Optional<String> appId,
            Optional<String> accountId,
            Optional<String> oauthAppId,
            Optional<String> appOverrideId,
            Map<String, Object> additionalProperties) {
        this.appId = appId;
        this.accountId = accountId;
        this.oauthAppId = oauthAppId;
        this.appOverrideId = appOverrideId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The app ID to validate against. Required unless account_id or app_override_id identifies the app.
     */
    @JsonProperty("app_id")
    public Optional<String> getAppId() {
        return appId;
    }

    /**
     * @return An existing account ID to reconnect. Must belong to the app identified by app_id.
     */
    @JsonProperty("account_id")
    public Optional<String> getAccountId() {
        return accountId;
    }

    /**
     * @return The OAuth app ID to validate against (if the token is for an OAuth app)
     */
    @JsonProperty("oauth_app_id")
    public Optional<String> getOauthAppId() {
        return oauthAppId;
    }

    /**
     * @return An app override ID. Selects the override's app, pre-defined custom fields, and OAuth client. With account_id, re-links the account to this override; it must belong to the account's app, and an override that pins a different OAuth client switches the account to that client when the reconnect flow completes. A conflicting app_id or oauth_app_id is an error. To resolve an override by name, list them with GET /v1/connect/{project_id}/app_overrides and match on name.
     */
    @JsonProperty("app_override_id")
    public Optional<String> getAppOverrideId() {
        return appOverrideId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TokensValidateRequest && equalTo((TokensValidateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TokensValidateRequest other) {
        return appId.equals(other.appId)
                && accountId.equals(other.accountId)
                && oauthAppId.equals(other.oauthAppId)
                && appOverrideId.equals(other.appOverrideId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.appId, this.accountId, this.oauthAppId, this.appOverrideId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> appId = Optional.empty();

        private Optional<String> accountId = Optional.empty();

        private Optional<String> oauthAppId = Optional.empty();

        private Optional<String> appOverrideId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TokensValidateRequest other) {
            appId(other.getAppId());
            accountId(other.getAccountId());
            oauthAppId(other.getOauthAppId());
            appOverrideId(other.getAppOverrideId());
            return this;
        }

        /**
         * <p>The app ID to validate against. Required unless account_id or app_override_id identifies the app.</p>
         */
        @JsonSetter(value = "app_id", nulls = Nulls.SKIP)
        public Builder appId(Optional<String> appId) {
            this.appId = appId;
            return this;
        }

        public Builder appId(String appId) {
            this.appId = Optional.ofNullable(appId);
            return this;
        }

        /**
         * <p>An existing account ID to reconnect. Must belong to the app identified by app_id.</p>
         */
        @JsonSetter(value = "account_id", nulls = Nulls.SKIP)
        public Builder accountId(Optional<String> accountId) {
            this.accountId = accountId;
            return this;
        }

        public Builder accountId(String accountId) {
            this.accountId = Optional.ofNullable(accountId);
            return this;
        }

        /**
         * <p>The OAuth app ID to validate against (if the token is for an OAuth app)</p>
         */
        @JsonSetter(value = "oauth_app_id", nulls = Nulls.SKIP)
        public Builder oauthAppId(Optional<String> oauthAppId) {
            this.oauthAppId = oauthAppId;
            return this;
        }

        public Builder oauthAppId(String oauthAppId) {
            this.oauthAppId = Optional.ofNullable(oauthAppId);
            return this;
        }

        /**
         * <p>An app override ID. Selects the override's app, pre-defined custom fields, and OAuth client. With account_id, re-links the account to this override; it must belong to the account's app, and an override that pins a different OAuth client switches the account to that client when the reconnect flow completes. A conflicting app_id or oauth_app_id is an error. To resolve an override by name, list them with GET /v1/connect/{project_id}/app_overrides and match on name.</p>
         */
        @JsonSetter(value = "app_override_id", nulls = Nulls.SKIP)
        public Builder appOverrideId(Optional<String> appOverrideId) {
            this.appOverrideId = appOverrideId;
            return this;
        }

        public Builder appOverrideId(String appOverrideId) {
            this.appOverrideId = Optional.ofNullable(appOverrideId);
            return this;
        }

        public TokensValidateRequest build() {
            return new TokensValidateRequest(appId, accountId, oauthAppId, appOverrideId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
