/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.accounts;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.accounts.requests.AccountsListByExternalUserRequest;
import com.pipedream.api.resources.accounts.requests.AccountsListRequest;
import com.pipedream.api.resources.accounts.requests.AccountsRetrieveRequest;
import com.pipedream.api.resources.accounts.requests.CreateAccountOpts;
import com.pipedream.api.types.Account;
import java.util.List;

public class AccountsClient {
    protected final ClientOptions clientOptions;

    private final RawAccountsClient rawClient;

    public AccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAccountsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAccountsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public SyncPagingIterable<Account> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public SyncPagingIterable<Account> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public SyncPagingIterable<Account> list(AccountsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public SyncPagingIterable<Account> list(AccountsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Connect a new account for an external user in the project
     */
    public Account create(CreateAccountOpts request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Connect a new account for an external user in the project
     */
    public Account create(CreateAccountOpts request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Get the details for a specific connected account
     */
    public Account retrieve(String accountId) {
        return this.rawClient.retrieve(accountId).body();
    }

    /**
     * Get the details for a specific connected account
     */
    public Account retrieve(String accountId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(accountId, requestOptions).body();
    }

    /**
     * Get the details for a specific connected account
     */
    public Account retrieve(String accountId, AccountsRetrieveRequest request) {
        return this.rawClient.retrieve(accountId, request).body();
    }

    /**
     * Get the details for a specific connected account
     */
    public Account retrieve(String accountId, AccountsRetrieveRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(accountId, request, requestOptions).body();
    }

    /**
     * Remove a connected account and its associated credentials
     */
    public void delete(String accountId) {
        this.rawClient.delete(accountId).body();
    }

    /**
     * Remove a connected account and its associated credentials
     */
    public void delete(String accountId, RequestOptions requestOptions) {
        this.rawClient.delete(accountId, requestOptions).body();
    }

    /**
     * Remove all connected accounts for a specific app
     */
    public void deleteByApp(String appId) {
        this.rawClient.deleteByApp(appId).body();
    }

    /**
     * Remove all connected accounts for a specific app
     */
    public void deleteByApp(String appId, RequestOptions requestOptions) {
        this.rawClient.deleteByApp(appId, requestOptions).body();
    }

    /**
     * List all connected accounts for a specific external user. Equivalent to GET /accounts with external_user_id filter but uses path-based routing.
     */
    public List<Account> listByExternalUser(String externalUserId) {
        return this.rawClient.listByExternalUser(externalUserId).body();
    }

    /**
     * List all connected accounts for a specific external user. Equivalent to GET /accounts with external_user_id filter but uses path-based routing.
     */
    public List<Account> listByExternalUser(String externalUserId, RequestOptions requestOptions) {
        return this.rawClient.listByExternalUser(externalUserId, requestOptions).body();
    }

    /**
     * List all connected accounts for a specific external user. Equivalent to GET /accounts with external_user_id filter but uses path-based routing.
     */
    public List<Account> listByExternalUser(String externalUserId, AccountsListByExternalUserRequest request) {
        return this.rawClient.listByExternalUser(externalUserId, request).body();
    }

    /**
     * List all connected accounts for a specific external user. Equivalent to GET /accounts with external_user_id filter but uses path-based routing.
     */
    public List<Account> listByExternalUser(
            String externalUserId, AccountsListByExternalUserRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listByExternalUser(externalUserId, request, requestOptions)
                .body();
    }
}
