/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.accounts;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.pipedream.api.core.BaseClientApiException;
import com.pipedream.api.core.BaseClientException;
import com.pipedream.api.core.BaseClientHttpResponse;
import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.MediaTypes;
import com.pipedream.api.core.ObjectMappers;
import com.pipedream.api.core.QueryStringMapper;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.errors.TooManyRequestsError;
import com.pipedream.api.resources.accounts.requests.CreateAccountOpts;
import com.pipedream.api.resources.accounts.requests.DeleteAccountsRequest;
import com.pipedream.api.resources.accounts.requests.DeleteByAppAccountsRequest;
import com.pipedream.api.resources.accounts.requests.ListAccountsRequest;
import com.pipedream.api.resources.accounts.requests.RetrieveAccountsRequest;
import com.pipedream.api.types.Account;
import com.pipedream.api.types.ListAccountsResponse;
import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawAccountsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawAccountsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public CompletableFuture<BaseClientHttpResponse<SyncPagingIterable<Account>>> list() {
        return list(ListAccountsRequest.builder().build());
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public CompletableFuture<BaseClientHttpResponse<SyncPagingIterable<Account>>> list(ListAccountsRequest request) {
        return list(request, null);
    }

    /**
     * Retrieve all connected accounts for the project with optional filtering
     */
    public CompletableFuture<BaseClientHttpResponse<SyncPagingIterable<Account>>> list(
            ListAccountsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("accounts");
        if (request.getExternalUserId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_user_id", request.getExternalUserId().get(), false);
        }
        if (request.getOauthAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "oauth_app_id", request.getOauthAppId().get(), false);
        }
        if (request.getAfter().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "after", request.getAfter().get(), false);
        }
        if (request.getBefore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "before", request.getBefore().get(), false);
        }
        if (request.getLimit().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "limit", request.getLimit().get(), false);
        }
        if (request.getApp().isPresent()) {
            QueryStringMapper.addQueryParameter(httpUrl, "app", request.getApp().get(), false);
        }
        if (request.getIncludeCredentials().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_credentials",
                    request.getIncludeCredentials().get(),
                    false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BaseClientHttpResponse<SyncPagingIterable<Account>>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        ListAccountsResponse parsedResponse =
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), ListAccountsResponse.class);
                        Optional<String> startingAfter =
                                parsedResponse.getPageInfo().getEndCursor();
                        ListAccountsRequest nextRequest = ListAccountsRequest.builder()
                                .from(request)
                                .after(startingAfter)
                                .build();
                        List<Account> result = parsedResponse.getData();
                        future.complete(new BaseClientHttpResponse<>(
                                new SyncPagingIterable<Account>(
                                        startingAfter.isPresent(), result, parsedResponse, () -> {
                                            try {
                                                return list(nextRequest, requestOptions)
                                                        .get()
                                                        .body();
                                            } catch (InterruptedException | ExecutionException e) {
                                                throw new RuntimeException(e);
                                            }
                                        }),
                                response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 429) {
                            future.completeExceptionally(new TooManyRequestsError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new BaseClientApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Connect a new account for an external user in the project
     */
    public CompletableFuture<BaseClientHttpResponse<Account>> create(CreateAccountOpts request) {
        return create(request, null);
    }

    /**
     * Connect a new account for an external user in the project
     */
    public CompletableFuture<BaseClientHttpResponse<Account>> create(
            CreateAccountOpts request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("accounts");
        if (request.getExternalUserId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_user_id", request.getExternalUserId().get(), false);
        }
        if (request.getOauthAppId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "oauth_app_id", request.getOauthAppId().get(), false);
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BaseClientHttpResponse<Account>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new BaseClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Account.class), response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 429) {
                            future.completeExceptionally(new TooManyRequestsError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new BaseClientApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Get the details for a specific connected account
     */
    public CompletableFuture<BaseClientHttpResponse<Account>> retrieve(String accountId) {
        return retrieve(accountId, RetrieveAccountsRequest.builder().build());
    }

    /**
     * Get the details for a specific connected account
     */
    public CompletableFuture<BaseClientHttpResponse<Account>> retrieve(
            String accountId, RetrieveAccountsRequest request) {
        return retrieve(accountId, request, null);
    }

    /**
     * Get the details for a specific connected account
     */
    public CompletableFuture<BaseClientHttpResponse<Account>> retrieve(
            String accountId, RetrieveAccountsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("accounts")
                .addPathSegment(accountId);
        if (request.getIncludeCredentials().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_credentials",
                    request.getIncludeCredentials().get(),
                    false);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BaseClientHttpResponse<Account>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new BaseClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Account.class), response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 429) {
                            future.completeExceptionally(new TooManyRequestsError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new BaseClientApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Remove a connected account and its associated credentials
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> delete(String accountId) {
        return delete(accountId, DeleteAccountsRequest.builder().build());
    }

    /**
     * Remove a connected account and its associated credentials
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> delete(String accountId, DeleteAccountsRequest request) {
        return delete(accountId, request, null);
    }

    /**
     * Remove a connected account and its associated credentials
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> delete(
            String accountId, DeleteAccountsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("accounts")
                .addPathSegment(accountId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BaseClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new BaseClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 429) {
                            future.completeExceptionally(new TooManyRequestsError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new BaseClientApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Remove all connected accounts for a specific app
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> deleteByApp(String appId) {
        return deleteByApp(appId, DeleteByAppAccountsRequest.builder().build());
    }

    /**
     * Remove all connected accounts for a specific app
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> deleteByApp(
            String appId, DeleteByAppAccountsRequest request) {
        return deleteByApp(appId, request, null);
    }

    /**
     * Remove all connected accounts for a specific app
     */
    public CompletableFuture<BaseClientHttpResponse<Void>> deleteByApp(
            String appId, DeleteByAppAccountsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("v1/connect")
                .addPathSegment(clientOptions.projectId())
                .addPathSegments("apps")
                .addPathSegment(appId)
                .addPathSegments("accounts")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<BaseClientHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new BaseClientHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        if (response.code() == 429) {
                            future.completeExceptionally(new TooManyRequestsError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    future.completeExceptionally(new BaseClientApiException(
                            "Error with status code " + response.code(),
                            response.code(),
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                            response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new BaseClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
