/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.projects.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.pipedream.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateProjectOpts.Builder.class)
public final class CreateProjectOpts {
    private final String name;

    private final Optional<String> appName;

    private final Optional<String> supportEmail;

    private final Optional<Boolean> connectRequireKeyAuthTest;

    private final Map<String, Object> additionalProperties;

    private CreateProjectOpts(
            String name,
            Optional<String> appName,
            Optional<String> supportEmail,
            Optional<Boolean> connectRequireKeyAuthTest,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.appName = appName;
        this.supportEmail = supportEmail;
        this.connectRequireKeyAuthTest = connectRequireKeyAuthTest;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the project
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return Display name for the Connect application
     */
    @JsonProperty("app_name")
    public Optional<String> getAppName() {
        return appName;
    }

    /**
     * @return Support email displayed to end users
     */
    @JsonProperty("support_email")
    public Optional<String> getSupportEmail() {
        return supportEmail;
    }

    /**
     * @return Send a test request to the upstream API when adding Connect accounts for key-based apps
     */
    @JsonProperty("connect_require_key_auth_test")
    public Optional<Boolean> getConnectRequireKeyAuthTest() {
        return connectRequireKeyAuthTest;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateProjectOpts && equalTo((CreateProjectOpts) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateProjectOpts other) {
        return name.equals(other.name)
                && appName.equals(other.appName)
                && supportEmail.equals(other.supportEmail)
                && connectRequireKeyAuthTest.equals(other.connectRequireKeyAuthTest);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.appName, this.supportEmail, this.connectRequireKeyAuthTest);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>Name of the project</p>
         */
        _FinalStage name(@NotNull String name);

        Builder from(CreateProjectOpts other);
    }

    public interface _FinalStage {
        CreateProjectOpts build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Display name for the Connect application</p>
         */
        _FinalStage appName(Optional<String> appName);

        _FinalStage appName(String appName);

        /**
         * <p>Support email displayed to end users</p>
         */
        _FinalStage supportEmail(Optional<String> supportEmail);

        _FinalStage supportEmail(String supportEmail);

        /**
         * <p>Send a test request to the upstream API when adding Connect accounts for key-based apps</p>
         */
        _FinalStage connectRequireKeyAuthTest(Optional<Boolean> connectRequireKeyAuthTest);

        _FinalStage connectRequireKeyAuthTest(Boolean connectRequireKeyAuthTest);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Optional<Boolean> connectRequireKeyAuthTest = Optional.empty();

        private Optional<String> supportEmail = Optional.empty();

        private Optional<String> appName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateProjectOpts other) {
            name(other.getName());
            appName(other.getAppName());
            supportEmail(other.getSupportEmail());
            connectRequireKeyAuthTest(other.getConnectRequireKeyAuthTest());
            return this;
        }

        /**
         * <p>Name of the project</p>
         * <p>Name of the project</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Send a test request to the upstream API when adding Connect accounts for key-based apps</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage connectRequireKeyAuthTest(Boolean connectRequireKeyAuthTest) {
            this.connectRequireKeyAuthTest = Optional.ofNullable(connectRequireKeyAuthTest);
            return this;
        }

        /**
         * <p>Send a test request to the upstream API when adding Connect accounts for key-based apps</p>
         */
        @java.lang.Override
        @JsonSetter(value = "connect_require_key_auth_test", nulls = Nulls.SKIP)
        public _FinalStage connectRequireKeyAuthTest(Optional<Boolean> connectRequireKeyAuthTest) {
            this.connectRequireKeyAuthTest = connectRequireKeyAuthTest;
            return this;
        }

        /**
         * <p>Support email displayed to end users</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage supportEmail(String supportEmail) {
            this.supportEmail = Optional.ofNullable(supportEmail);
            return this;
        }

        /**
         * <p>Support email displayed to end users</p>
         */
        @java.lang.Override
        @JsonSetter(value = "support_email", nulls = Nulls.SKIP)
        public _FinalStage supportEmail(Optional<String> supportEmail) {
            this.supportEmail = supportEmail;
            return this;
        }

        /**
         * <p>Display name for the Connect application</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage appName(String appName) {
            this.appName = Optional.ofNullable(appName);
            return this;
        }

        /**
         * <p>Display name for the Connect application</p>
         */
        @java.lang.Override
        @JsonSetter(value = "app_name", nulls = Nulls.SKIP)
        public _FinalStage appName(Optional<String> appName) {
            this.appName = appName;
            return this;
        }

        @java.lang.Override
        public CreateProjectOpts build() {
            return new CreateProjectOpts(name, appName, supportEmail, connectRequireKeyAuthTest, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
