/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.apps;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.apps.requests.ListAppsRequest;
import com.pipedream.api.resources.apps.requests.RetrieveAppsRequest;
import com.pipedream.api.types.App;
import com.pipedream.api.types.GetAppResponse;

public class AppsClient {
    protected final ClientOptions clientOptions;

    private final RawAppsClient rawClient;

    public AppsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawAppsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawAppsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all available apps with optional filtering and sorting
     */
    public SyncPagingIterable<App> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve all available apps with optional filtering and sorting
     */
    public SyncPagingIterable<App> list(ListAppsRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve all available apps with optional filtering and sorting
     */
    public SyncPagingIterable<App> list(ListAppsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Get detailed information about a specific app by ID or name slug
     */
    public GetAppResponse retrieve(String appId) {
        return this.rawClient.retrieve(appId).body();
    }

    /**
     * Get detailed information about a specific app by ID or name slug
     */
    public GetAppResponse retrieve(String appId, RetrieveAppsRequest request) {
        return this.rawClient.retrieve(appId, request).body();
    }

    /**
     * Get detailed information about a specific app by ID or name slug
     */
    public GetAppResponse retrieve(String appId, RetrieveAppsRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(appId, request, requestOptions).body();
    }
}
