/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.actions;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.actions.requests.ConfigurePropActionsRequest;
import com.pipedream.api.resources.actions.requests.ListActionsRequest;
import com.pipedream.api.resources.actions.requests.ReloadPropsActionsRequest;
import com.pipedream.api.resources.actions.requests.RetrieveActionsRequest;
import com.pipedream.api.resources.actions.requests.RunActionOpts;
import com.pipedream.api.types.Component;
import com.pipedream.api.types.ConfigurePropResponse;
import com.pipedream.api.types.ReloadPropsResponse;
import com.pipedream.api.types.RunActionResponse;

public class ActionsClient {
    protected final ClientOptions clientOptions;

    private final RawActionsClient rawClient;

    public ActionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawActionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawActionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public SyncPagingIterable<Component> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public SyncPagingIterable<Component> list(ListActionsRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public SyncPagingIterable<Component> list(ListActionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Get detailed configuration for a specific action by its key
     */
    public Component retrieve(String componentId) {
        return this.rawClient.retrieve(componentId).body();
    }

    /**
     * Get detailed configuration for a specific action by its key
     */
    public Component retrieve(String componentId, RetrieveActionsRequest request) {
        return this.rawClient.retrieve(componentId, request).body();
    }

    /**
     * Get detailed configuration for a specific action by its key
     */
    public Component retrieve(String componentId, RetrieveActionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.retrieve(componentId, request, requestOptions).body();
    }

    /**
     * Retrieve remote options for a given prop for a action
     */
    public ConfigurePropResponse configureProp(ConfigurePropActionsRequest request) {
        return this.rawClient.configureProp(request).body();
    }

    /**
     * Retrieve remote options for a given prop for a action
     */
    public ConfigurePropResponse configureProp(ConfigurePropActionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.configureProp(request, requestOptions).body();
    }

    /**
     * Reload the prop definition based on the currently configured props
     */
    public ReloadPropsResponse reloadProps(ReloadPropsActionsRequest request) {
        return this.rawClient.reloadProps(request).body();
    }

    /**
     * Reload the prop definition based on the currently configured props
     */
    public ReloadPropsResponse reloadProps(ReloadPropsActionsRequest request, RequestOptions requestOptions) {
        return this.rawClient.reloadProps(request, requestOptions).body();
    }

    /**
     * Execute an action with the provided configuration and return results
     */
    public RunActionResponse run(RunActionOpts request) {
        return this.rawClient.run(request).body();
    }

    /**
     * Execute an action with the provided configuration and return results
     */
    public RunActionResponse run(RunActionOpts request, RequestOptions requestOptions) {
        return this.rawClient.run(request, requestOptions).body();
    }
}
