/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.actions;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.core.pagination.SyncPagingIterable;
import com.pipedream.api.resources.actions.requests.ActionsListRequest;
import com.pipedream.api.resources.actions.requests.RunActionOpts;
import com.pipedream.api.types.Component;
import com.pipedream.api.types.ConfigurePropOpts;
import com.pipedream.api.types.ConfigurePropResponse;
import com.pipedream.api.types.ReloadPropsOpts;
import com.pipedream.api.types.ReloadPropsResponse;
import com.pipedream.api.types.RunActionResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncActionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawActionsClient rawClient;

    public AsyncActionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawActionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawActionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public CompletableFuture<SyncPagingIterable<Component>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public CompletableFuture<SyncPagingIterable<Component>> list(ActionsListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve available actions with optional search and app filtering
     */
    public CompletableFuture<SyncPagingIterable<Component>> list(
            ActionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get detailed configuration for a specific action by its key
     */
    public CompletableFuture<Component> retrieve(String componentId) {
        return this.rawClient.retrieve(componentId).thenApply(response -> response.body());
    }

    /**
     * Get detailed configuration for a specific action by its key
     */
    public CompletableFuture<Component> retrieve(String componentId, RequestOptions requestOptions) {
        return this.rawClient.retrieve(componentId, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve remote options for a given prop for a action
     */
    public CompletableFuture<ConfigurePropResponse> configureProp(ConfigurePropOpts request) {
        return this.rawClient.configureProp(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve remote options for a given prop for a action
     */
    public CompletableFuture<ConfigurePropResponse> configureProp(
            ConfigurePropOpts request, RequestOptions requestOptions) {
        return this.rawClient.configureProp(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Reload the prop definition based on the currently configured props
     */
    public CompletableFuture<ReloadPropsResponse> reloadProps(ReloadPropsOpts request) {
        return this.rawClient.reloadProps(request).thenApply(response -> response.body());
    }

    /**
     * Reload the prop definition based on the currently configured props
     */
    public CompletableFuture<ReloadPropsResponse> reloadProps(ReloadPropsOpts request, RequestOptions requestOptions) {
        return this.rawClient.reloadProps(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Execute an action with the provided configuration and return results
     */
    public CompletableFuture<RunActionResponse> run(RunActionOpts request) {
        return this.rawClient.run(request).thenApply(response -> response.body());
    }

    /**
     * Execute an action with the provided configuration and return results
     */
    public CompletableFuture<RunActionResponse> run(RunActionOpts request, RequestOptions requestOptions) {
        return this.rawClient.run(request, requestOptions).thenApply(response -> response.body());
    }
}
