/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.pipedream.api.resources.appcategories;

import com.pipedream.api.core.ClientOptions;
import com.pipedream.api.core.RequestOptions;
import com.pipedream.api.types.AppCategory;
import java.util.List;
import java.util.concurrent.CompletableFuture;

public class AsyncAppCategoriesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAppCategoriesClient rawClient;

    public AsyncAppCategoriesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAppCategoriesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAppCategoriesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all available categories for integrated apps
     */
    public CompletableFuture<List<AppCategory>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve all available categories for integrated apps
     */
    public CompletableFuture<List<AppCategory>> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Get details of a specific app category by its ID
     */
    public CompletableFuture<AppCategory> retrieve(String id) {
        return this.rawClient.retrieve(id).thenApply(response -> response.body());
    }

    /**
     * Get details of a specific app category by its ID
     */
    public CompletableFuture<AppCategory> retrieve(String id, RequestOptions requestOptions) {
        return this.rawClient.retrieve(id, requestOptions).thenApply(response -> response.body());
    }
}
